name: Bug report
description: Report incorrect behavior with reproducible steps.
title: "[Bug] "
labels: ["type:bug"]
body:
  - type: textarea
    id: current
    attributes:
      label: Current behavior
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should happen?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Impact and scope
      description: Which component(s) are affected?
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria for fix
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true
  - type: textarea
    id: tests
    attributes:
      label: Test plan
      description: Which tests prove the bug is fixed?
    validations:
      required: true
