name: Feature request
description: Propose a new feature with acceptance criteria and tests.
title: "[Feature] "
labels: ["type:feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What user problem are we solving?
    validations:
      required: true
  - type: textarea
    id: outcome
    attributes:
      label: Expected outcome
      description: What does success look like?
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: List concrete pass/fail criteria.
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true
  - type: textarea
    id: nongoals
    attributes:
      label: Out of scope
      description: What should not be changed in this issue?
    validations:
      required: true
  - type: textarea
    id: tests
    attributes:
      label: Test plan
      description: Unit/integration/smoke tests expected for this issue.
    validations:
      required: true
